---
apiVersion: v1
kind: Service
metadata:
  name: ceph-mon-1
spec:
  clusterIP: None
  ports:
  - name: rbd
    port: 6789
    protocol: TCP
    targetPort: 6789
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: ceph-mon-2
spec:
  clusterIP: None
  ports:
  - name: rbd
    port: 6789
    protocol: TCP
    targetPort: 6789
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: ceph-mon-3
spec:
  clusterIP: None
  ports:
  - name: rbd
    port: 6789
    protocol: TCP
    targetPort: 6789
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}